### ISSUE TITLE
Optional row or col in rules

### ISSUE THREAD

**Issue by Righolt** [VaccineAndDrugEvaluationCentre/rosewood#12]
Should a row and col declaration be optional and flexible in the rule section, especially relating to the following specs:
- The order of `row` and `col` can be switched.
- When `row` or `col` is missing the command applies to all rows or columns.

Ease of use should be the leading guide here, but in @DrGo 's words
>ease of use has multi-dimensions and includes ease of writing, reading and maintaining the code (which includes not having to diagnose and fix with subtle bugs). These aspects may not become clear until people start to write code (by hand) and a lot of it and others having to review it. Ease of use cannot be reduced to typing fewer characters or code aesthetics.

**Comment by Righolt** [comment]
@DrGo @barretmonchka Any comments?

**Comment by Righolt** [comment]
@DrGo @barretmonchka Let's try to finalize this, so we can move on with development.

In my eyes lower barriers to manual editing (allowing the switching or omission in the specs above), the easier it is. This would necessitate a little more complexity on the parsing (rw table --> output table), but that is probably worth it, and because of the limited permutations easy to test.

**Comment by Righolt** [comment]
@DrGo This is the last open issue in the Rosewood language definition.

**Comment by rbisewski** [comment]
Well, right now `row` and `col` can be switched, in master. I'll work on adjusting the code to handle the other style.

**Comment by Righolt** [comment]
Please first check what the code does and does not support in all the definitions (see rosewood.md), then we can decide about changing the code or whether spec changes are in order. (Best to also include more tests in the tests list for every command you check)
