### ISSUE TITLE
formal specs for Rosewood v0.2

### ISSUE THREAD

**Issue by DrGo** [VaccineAndDrugEvaluationCentre/rosewood#13]
@barretmonchka @Righolt 
See the updated specs https://github.com/VaccineAndDrugEvaluationCentre/rosewood/blob/master/rosewood-spec.md.
Decided to use v0.2 for this version to indicate that it is still work in progress.  The current version would be v0.1.
The check box in the grammar elements list indicates that the feature is implemented in a new branch (refactorSpans)  that is going to be Carpenter 0.4.5. 

Pls open a separate issue for each bug/change you would like to see,

**Comment by Righolt** [comment]
Looks good overall, I added links back to the old "specs" and propose to leave that as a lay summary/non-technical doc that we could use in conjunction (rosewood-spec being leading though). I opened some issues to discuss discrepancies.
